# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 19:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2016, 2, 15, 19, 25, 34, 837001, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=60),
        ),
    ]
