# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0002_auto_20160215_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
