# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 18:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0003_auto_20160215_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='diases_name',
            field=models.CharField(default=datetime.datetime(2016, 2, 21, 18, 39, 8, 6127, tzinfo=utc), max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='symptoms',
            field=models.TextField(default=1995, max_length=400),
            preserve_default=False,
        ),
    ]
