# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0004_auto_20160221_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cell_phone',
            field=models.CharField(default=1996, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(default=1992, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital_name',
            field=models.CharField(default='ek@g.rit.edu', max_length=250),
            preserve_default=False,
        ),
    ]
