# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0005_auto_20160221_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=20)),
                ('patients', models.CharField(max_length=60)),
            ],
        ),
    ]
