# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0006_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='doctors',
            field=models.TextField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='stuff',
            field=models.TextField(default='Patient 0'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='patients',
            field=models.TextField(),
        ),
    ]
