# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0008_auto_20160228_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('patients', models.CharField(max_length=250)),
                ('doctor', models.CharField(max_length=250)),
                ('reason', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('cell_phone', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('hospital_name', models.CharField(max_length=250)),
                ('patients', models.TextField(verbose_name=400)),
            ],
        ),
    ]
