# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0009_apoitment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Male', max_length=250),
            preserve_default=False,
        ),
    ]
