# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0010_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.CharField(default='Zoidberg', max_length=250),
            preserve_default=False,
        ),
    ]
