# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0011_patient_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='doctors',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='patients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HealthNet.Patient'),
        ),
    ]
