# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0012_auto_20160307_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='doctors',
            field=models.ForeignKey(default=99, on_delete=django.db.models.deletion.CASCADE, to='HealthNet.Doctor'),
            preserve_default=False,
        ),
    ]
