# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0014_auto_20160307_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='patients',
        ),
        migrations.AddField(
            model_name='hospital',
            name='patients',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HealthNet.Patient'),
            preserve_default=False,
        ),
    ]
