# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0016_auto_20160307_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='doctors',
        ),
        migrations.AddField(
            model_name='hospital',
            name='doctors',
            field=models.ManyToManyField(to='HealthNet.Doctor'),
        ),
    ]
