# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-07 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0017_auto_20160307_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('cell_phone', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('hospital_name', models.CharField(max_length=250)),
                ('patients', models.TextField(verbose_name=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='stuff',
        ),
        migrations.AddField(
            model_name='hospital',
            name='stuff',
            field=models.ManyToManyField(to='HealthNet.Stuff'),
        ),
    ]
