# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0018_auto_20160307_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('action', models.CharField(max_length=250)),
                ('who_did', models.CharField(max_length=250)),
                ('what_happened', models.CharField(max_length=250)),
            ],
        ),
    ]
