# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0019_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='assigned_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
