# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0020_patient_assigned_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='patients',
            new_name='patients_list',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='doctor',
            new_name='_doctor',
        ),
        migrations.RenameField(
            model_name='stuff',
            old_name='patients',
            new_name='patients_stuff_list',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='patients',
        ),
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(to='HealthNet.Patient'),
        ),
    ]
