# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0022_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.RenameField(
            model_name='apoitment',
            old_name='date',
            new_name='date_end',
        ),
        migrations.AddField(
            model_name='apoitment',
            name='date_start',
            field=models.DateTimeField(default=1991),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
