# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0022_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('title', models.CharField(max_length=250)),
                ('doctor', models.CharField(max_length=250)),
                ('patient', models.CharField(max_length=250)),
            ],
        ),
    ]
