# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0023_scheduler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduler',
            name='end_date',
        ),
    ]
