# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0024_auto_20160324_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apoitment',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='apoitment',
            name='date_start',
            field=models.DateTimeField(),
        ),
    ]
