# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0025_auto_20160324_0106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apoitment',
        ),
    ]
