# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0026_administration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=250)),
                ('receiver', models.CharField(max_length=250)),
                ('text_body', models.CharField(max_length=500)),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
    ]
