# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0027_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apoitment',
            old_name='doctor',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='apoitment',
            name='patients',
        ),
        migrations.AddField(
            model_name='doctor',
            name='apoitment_list',
            field=models.ManyToManyField(to='HealthNet.Apoitment'),
        ),
    ]
