# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0028_auto_20160425_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('cell_phone', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('hospital_name', models.CharField(max_length=250)),
                ('apoitment_list', models.ManyToManyField(to='HealthNet.Apoitment')),
                ('patients', models.ManyToManyField(to='HealthNet.Patient')),
            ],
        ),
    ]
