# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0029_nurse'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='nurses',
            field=models.ManyToManyField(to='HealthNet.Nurse'),
        ),
    ]
