# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0031_auto_20160506_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='message_list',
            field=models.ManyToManyField(to='HealthNet.Messages'),
        ),
    ]
