# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0032_patient_message_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='message_list',
            new_name='patient_message_list',
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_message_list',
            field=models.ManyToManyField(to='HealthNet.Messages'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='nurse_messages',
            field=models.ManyToManyField(to='HealthNet.Messages'),
        ),
    ]
