# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0033_auto_20160510_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='time_stamp',
            field=models.CharField(max_length=250),
        ),
    ]
