# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthNet', '0034_auto_20160511_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_message_list',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='nurse_messages',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_message_list',
        ),
    ]
